name = "mdv5a"
path = "models/md_v5a_d_pp.onnx"
url = "https://zenodo.org/records/15056594/files/md_v5a_d_pp.onnx?download=1"
imgsz = 1280
classes = ["Animal", "Person", "Vehicle"]
md5 = "7df84e4900ac2eaabd91a49e56e21bc3"
