name = "mdv6-yolov9e-1280"
path = "models/MDV6-yolov9e-1280_d_pp.onnx"
url = "https://megascops.app/models/MDV6-yolov9e-1280_d_pp.onnx"
imgsz = 1280
classes = ["Animal", "Person", "Vehicle"]
md5 = "bed07acca5ab407ad3158147cc5f7977"
