name = "mdv6-yolov9e"
path = "models/MDV6-yolov9e_d_pp.onnx"
url = "https://megascops.app/models/MDV6-yolov9e_d_pp.onnx"
imgsz = 640
classes = ["Animal", "Person", "Vehicle"]
md5 = "6df392ab2cc3bed9cd88db83022b93c4"
