name = "mdv6-rtdetr-s"
path = "models/MDV6-rtdetr_s.onnx"
imgsz = 640
classes = ["Animal", "Person", "Vehicle"]
url = "https://megascops.app/models/MDV6-rtdetr_s.onnx"
md5 = "8be5ee01cdf55bcbec3eb3629d66d8b4"
