name = "mdv6-rtdetr-x"
path = "models/MDV6-rtdetr_x.onnx"
imgsz = 640
classes = ["Animal", "Person", "Vehicle"]
url = "https://megascops.app/models/MDV6-rtdetr_x.onnx"
md5 = "bf6507e22b48de9b018f41a4312ba346"
