name = "mdv6-yolov10n"
path = "models/MDV6-yolov10n.onnx"
url = "https://megascops.app/models/MDV6-yolov10n.onnx"
imgsz = 640
classes = ["Animal", "Person", "Vehicle"]
md5 = "f1fa191cbd8fd1bae8673228d7574cbe"
