name = "mdv6-yolov10x"
path = "models/MDV6-yolov10x.onnx"
url = "https://megascops.app/models/MDV6-yolov10x.onnx"
imgsz = 640
classes = ["Animal", "Person", "Vehicle"]
md5 = "a082fad7187b4c5518198efdb0989b99"
